import { ReactNode } from "react";
import NavBar from "./components/NavBar";

export const metadata = {
  title: "Aqua Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode[] }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
